name: CWBD
on:
  push:
    branches: [ main ]
    
  pull_request:
    branches: [main, satish-dev]
jobs:
  container-cwbd-job:
    runs-on: ubuntu-latest
    
    container:
      image: python:latest
      options: --user root
      
      env:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v3 

      - name: Check work folder
        run: pwd

      - name: run LS
        run: ls -R