name: Update_repo
on:
  workflow_dispatch:
     
jobs:
  update-component:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3 

      - name: Check work folder
        run: pwd