name: Update_repo
on:
  workflow_dispatch:
       
    schedule:
    - cron: "0 15 * * 1-5"
  
jobs:
  update-component:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3 

      - name: Check work folder
        run: pwd

      - name: Update Repo
        with:
          github-token: ${{ secrets.MY_TOKEN }}
          run: git submodule update --remote

      - name: Commit chnages
        with:
          github-token: ${{ secrets.MY_TOKEN }}
          run: git add . && git commit -m "update new version" && git push